PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `tag` (
        `id`   INTEGER PRIMARY KEY AUTOINCREMENT,
        `name` TEXT NOT NULL
);
INSERT INTO tag VALUES(1,'animal');
COMMIT;
